=== Recherche de la solution adaptée

La problématique concernant le changement de configuration des agents Zabbix en place sur le réseau a été l'élément déclencheur de cette recherche. Il y avait plus de deux cents configurations à modifier. Un nombre important d'actions redondantes aurait dû être effectué. Nous avons souhaité automatiser et rationnaliser ces actions, notions importantes de la mouvance DevOps.
 +
Pour ce genre d'actes, il existe des solutions de gestion de configuration. Ce sont des outils puissants puisqu'ils offrent la possibilité de copier des scripts et de les exécuter sur un nombre illimité d'ordinateurs et en parallèle. Pour nous, l'outil doit posséder une installation légère, être simple dans sa configuration de requêtes et pouvoir gérer les environnements Linux et Windows.
 +
Les recherches nous ont amenés à choisir _Ansible_, solution open source implémentée en langage Python. Nous avons été motivé par plusieurs points. Premièrement, c'est un outil dit "agentless" ; ça signifie que l'outil n'a besoin que d'un serveur pour effectuer ces actions. Les solutions réputées telles que _Chef_ et _Puppet_ utilisent un serveur et des agents sur chaque noeud à gérer, comme le logiciel Zabbix. Ensuite, Ansible utilise _YAML_, un format de représentation des données et peut gérer les environnements _Linux_ et _Windows_. Enfin, cette solution est gratuite pour l'utilisation que nous souhaitons en faire.

=== Mise en place

Avant de mettre en place la solution sur l'infrastructure, nous avons effectué divers tests dans un environnement dédié. Son installation est très aisé puisqu'il s'agit d'un seul logiciel. Le serveur est uniquement installable dans un environnement Linux.
Ansible utilise le protocole de communication _SSH_ -Secure Shell- pour transmettre ces requêtes vers les environnements Linux. Ce protocole réseau est un protocole de communications sécurisées basé sur l'utilisation du couple clef privée et clef publique. Un couple de clefs a été mis en place pour l'utilisation de ce service sur notre infrastructure. La clef publique a été transmise à chaque hôte Linux de notre architecture réseau.
Pour les environnements Windows, ce protocole de sécurisation n'est pas implémenté. Il faut donc utiliser une fonctionnalité propriétaire appelé _WinRM_ -Windows Remote Manager. C'est un protocole de gestion à distance qui permet la communication entre deux matériels réseaux.
Ansible embarque diverses modules comme le ping, fonction qui retourne si la connexion entre le serveur et le noeud est fonctionnelle ou non.
 +
Dans notre cas, notre but était d'automatiser la mise à jour ou l'installation des agents sur les environnements à monitorer et de les configurer. Nous avons créé deux scripts, un pour les environnements Linux et l'autre pour les environnements Windows.
Le premier devait installer la plus haute version possible sur chaque distribution Linux (_Ubuntu_, _Debian_ et _Redhat_/_CentOS_). Quand au second, il devait détecter si l'environnement Windows était en 32 bits ou en 64 bits et lui installé la version en adéquation avec les résultats. Des scripts robustes et stables ont été implémentés afin d'éviter les pertes de temps inutiles dans le débogage de l'exécution.
Grâce à Ansible, nous avons pu copier nos scripts sur chaque environnement et les exécuter.

=== Apports et limites de l'outil

Ce logiciel a été d'une grande aide dans la migration définitive de notre nouveau serveur Zabbix. Il nous a permis de déployer les nouvelles configurations sur plus de deux cents hôtes. Le gain de temps a été positif pour le pôle.
D'autres utilisations en ont découlé comme effectuer des mises à jour d'un script ou des montées de version d'un logiciel sur tous les environnements impactés.
 +
Cependant, cet outil possède des failles. Elles concernent les destinataires étant sous l'environnement Windows. Pour rendre leur logiciel fonctionnel sur cet environnement, les concepteurs ont dû utiliser une solution de secours au protocole SSH, à savoir WinRM. Malheureusement, cette fonctionnalité n'est pas native et dépend d'une version du logiciel _PowerShell_. Or, certaines versions de ce système d'exploitation ne permettent pas la mise à jour de ce logiciel et donc l'utilisation d'Ansible.
Néanmoins, notre infrastructure possède un nombre limité d'hôtes possédant ce problème.
