=== Infrastructure

Historiquement, SQLi Group travaille avec des environnements virtualisés. Son objectif consiste à faire fonctionner plusieurs système d'exploitation sur un ou plusieurs serveurs [4]. Beaucoup d'entreprise de tout secteur adopte ce système car il permet une réduction des coût et rend la gestion plus aisée. L'infrastructure d'ISC France est en évolution depuis l'appropriation de la mouvance DevOps. Des investissements infrastructuraux de la part de la direction ont été ordonnés. Ils ont provoqué une infrastructure hétérogène et plus difficile à administrer.

_VMWare ESXi_ est la solution la plus ancienne de l'entreprise. Cette plateforme propriétaire est un hyperviseur de type I signifiant qu'il est installé en lieu et place d'un système d'exploitation, il permet une gestion plus efficace des environnements virtualisés tel que la migration dynamique des machines virtuels [5].
_OpenStack_ est la seconde plateforme de virtualisation utilisée par ISC France. Cette solution possède l'avantage d'être stable, déjà utilisée par des grandes entreprises aux architectures massives et complexes, et d'être _open source_, la rendant flexible à chaque utilisation [6].

Les deux dernières solutions sont basées sur l'isolation des processus dans le noyau _Linux_. Le système d'exploitation invité, appelé _container_, est contenu dans un processus isolé des autres à l'aide de deux fonctionnalités du noyau, _Cgroups_ et _Namespaces_ [7]. Le premier est _OpenVZ_, un noyau modifié Linux[8]. Ce logiciel a été l'un des premiers à utiliser la technologie de _containerisation_. Il apparait un peu en retrait de nos jours. Le second est _Docker_ [9], devenu en quelques années l'outil de référence dans le mouvement DevOps. Il a l'avantage de s'installer sur tous les noyaux linux comme un logiciel standard et va bientôt être supporté nativement dans les environnements _Windows_ et _MAC OS_.
A court terme, l'entrprise a pour but de migrer les machines virtuelles des VMWare ESXi vers OpenStack et les environnements virtuels d'OpenVZ vers Docker.

Au sein du pôle CRCI, de nouvelles pratiques ont émergé en lien avec la culture DevOps.
L'automatisation du déploiement des environnements de production est la première. Le but est de pouvoir détruire une machine virtuel en ayant la possibilité de la redéployer à l'identique en un minimum de temps. Cette automatisation est implémentée par l'intermédiaire de programmes développés en langage de script (Bash, Python).
La seconde pratique est la configuration adéquat d'un logiciel de mesure permettant de récupérer les ressources utilisées par une machine virtuelle abritant un projet. D'un point de vu du CRCI, les mesures à calculer sont au niveau physique de la machine virtuelle (la quantité de memoire vive (RAM) ou le stockage minimum nécessaire pour une application d'un projet). Ces relevés peuvent être remontés aux équipes de développement pour optimiser l'application.
De plus, ce genre de logiciel est utile pour le pôle car il permet d'effectuer une surveillance de l'infrastructure dans son ensemble et d'envoyer une notification aux infogérants.

Ce type d'application est très important pour les infogérants. Comme l'évoque l'article de  [10] ... .
