=== Infrastructure

Historiquement, SQLi Group travaille avec des environnements virtualisés. Son objectif consiste à faire fonctionner plusieurs systèmes d'exploitation sur un ou plusieurs serveurs [4]. De nombreuses entreprises de tout secteur adoptent ce système car il permet une réduction des coûts et rend la gestion plus aisée. L'infrastructure d'ISC France est en évolution depuis l'appropriation de la mouvance DevOps. Des investissements infrastructuraux de la part de la direction ont été ordonnés. Ils ont provoqué une infrastructure hétérogène et plus difficile à administrer.

_VMWare ESXi_ est la solution de virtualisation la plus ancienne de l'entreprise. Cette plateforme propriétaire est un hyperviseur de type I signifiant qu'il est installé en lieu et place d'un système d'exploitation. Il permet une gestion plus efficace des environnements virtualisés tel que la migration dynamique des machines virtuels [5].
_OpenStack_ est la seconde plateforme de virtualisation utilisée par ISC France. Malgré sa jeunesse, cette solution est stable. Elle est déjà utilisée par des grandes entreprises aux architectures massives et complexes [6]. De plus, c'est un logiciel _open source_ avec une communauté de plus en plus importante.
 +
En plus du système de virtualisation dit classique, l'entreprise utilise deux solutions basées sur l'isolation des processus dans le noyau _Linux_. Le système d'exploitation invité, appelé _container_, est contenu dans un processus isolé des autres à l'aide de deux fonctionnalités du noyau Linux [7].
Le premier est _OpenVZ_, un noyau modifié Linux[8]. Ce logiciel a été l'un des premiers à utiliser la technologie de _containerisation_. Il apparait un peu en retrait de nos jours.
Le second est _Docker_ [9], devenu en quelques années un des outils de référence dans le mouvement DevOps. Il a l'avantage de s'installer sur tous les noyaux Linux comme un logiciel standard et va bientôt être supporté nativement dans les environnements _Windows_ et _MAC OS_.
 +
A court terme, l'entreprise a pour but de migrer les machines virtuelles des VMWare ESXi vers OpenStack et les environnements virtuels d'OpenVZ vers Docker.

<<<

Au sein du pôle CRCI, de nouvelles pratiques ont émergé en lien avec la culture DevOps.
 +
L'automatisation du déploiement des environnements de production est la première. Le but est de pouvoir détruire une machine virtuelle avec la possibilité de la redéployer à l'identique en un minimum de temps. OpenStack est connu pour permettre nativement cette automatisation. A la création de l'instance virtuelle, un script (Bash, Python ou Perl), passé en paramètre, s'exécute et rend la machine utilisable dès son premier lancement.
 +
La seconde pratique est la configuration adéquate d'un logiciel de mesure permettant de récupérer les ressources utilisées par une machine virtuelle. D'un point de vue du CRCI, les mesures à calculer sont au niveau physique de la machine virtuelle (la quantité de memoires vives (RAM) ou le stockage minimum nécessaire pour une application d'un projet). Ces relevés peuvent être remontés aux équipes de développement pour optimiser l'application.
De plus, ce type de logiciel est utile pour le pôle car il permet d'effectuer une surveillance de l'infrastructure dans son ensemble et d'envoyer une notification aux collaborateurs du pôle en cas de problème.
