=== Infrastructure

Historiquement, SQLi Group travaille avec des environnements virtualisés. Le principe de la _virtualisation_ consiste à faire fonctionner plusieurs systèmes d'exploitation sur un ou plusieurs serveurs [4]. De nombreuses entreprises de tout secteur adoptent cette technologie puisqu'elle permet de réduire les coûts et de rendre la gestion plus aisée. L'infrastructure d'ISC France est en évolution depuis l'appropriation de la mouvance DevOps. Des investissements de la part de la direction ont été ordonnés. Ce choix a entrainé une hétérogénéité dans l'infrastructure la rendant plus compliquée à administrer.

_VMWare ESXi_ est la solution de virtualisation la plus ancienne de l'entité. Cette plateforme propriétaire est un hyperviseur de type I signifiant qu'il est installé en lieu et place d'un système d'exploitation. Il permet une gestion plus efficace des environnements virtualisés tel que la migration dynamique des machines virtuels [5].
_OpenStack_ est la seconde plateforme de virtualisation utilisée par ISC France. Malgré sa jeunesse, cette solution est stable. Elle est déjà utilisée par des grandes entreprises aux architectures massives et complexes [6]. De plus, c'est un logiciel _open source_ avec une communauté de plus en plus importante.
 +
En plus du système de virtualisation dit "classique", l'entreprise utilise deux solutions basées sur l'isolation des processus dans le noyau _Linux_. Le système d'exploitation invité, appelé _container_, est contenu dans un processus isolé des autres processus s'exécutant sur l'hôte, à l'aide de deux fonctionnalités du noyau Linux [7].
Le premier outil est _OpenVZ_, un noyau modifié Linux [8]. Ce logiciel a été l'un des premiers à utiliser la technologie de _containerisation_. Il apparait un peu en retrait de nos jours.
Le second est _Docker_ [9], devenu en quelques années une des solutions de référence dans le mouvement DevOps. Il a l'avantage de s'installer sur tous les noyaux Linux comme un logiciel standard et va bientôt être supporté nativement dans les environnements _Windows_ et _MAC OS_.
 +
A court terme, l'entreprise a pour but de migrer les machines virtuelles des VMWare ESXi vers OpenStack et les environnements virtuels d'OpenVZ vers Docker.

<<<

Au sein du pôle CRCI, de nouvelles pratiques ont émergé en lien avec la culture DevOps.
 +
L'automatisation du déploiement des environnements de production est la première. Le but est de pouvoir détruire une machine virtuelle à tout instant et de pouvoir la redéployer à l'identique en un minimum de temps. OpenStack est connu pour permettre nativement cette automatisation. A la création de l'instance virtuelle, un script (Bash, Python ou Perl), passé en paramètre, s'exécute et rend la machine utilisable dès son premier lancement.
 +
La seconde pratique est la configuration adéquate d'un logiciel de mesure permettant de récupérer les ressources utilisées par une machine virtuelle. D'un point de vue des ingénieurs de l'équipe, les mesures à monitorer sont au niveau physique de la machine virtuelle, comme la quantité de mémoires vives (RAM) utilisé par l'environnement. Ces relevés peuvent être remontés aux équipes de développement pour optimiser l'application.
De plus, ce type de logiciel est utile pour le pôle car il permet d'effectuer une surveillance de l'infrastructure dans son ensemble et d'envoyer une notification à l'équipe en cas de dysfonctionnement.
