=== ISC France

SQLi Group est représenté à Bordeaux par deux entités de SQLI Enterprise, une agence et une sous-entité appelée _ISC_ (Innovative Service Centers). Cette dernière est le centre de service de SQLi Group. Il y en a quatre au sein du groupe (deux en France et deux au Maroc). ISC différe d'une agence dans le fait que les collaborateurs travaillent dans les locaux de l'entité.
Cette donnée oblige ces structures de posséder une infrastructure réseau et système conséquente pour reproduire au maximum les environnements de leur clients.

<<<

ISC France est un l'ensemble des deux centres de services français, Bordeaux et Nantes. Ils partagent la même direction, travaillent ensemble sur certains projets et possède une infrastructure centrale. En effet, Bordeaux héberge et gère un nombre important de serveurs partagé entre les deux entités.
Ces équipes mènent une veille technologique constante leur permettant de mener des évolutions sur les méthodes de travail et les solutions utilisées par les collaborateurs. Son dynamisme en fait la locomotive de SQLi Group qui se permet de diffuser ces nouvelles avancées à tous les collaborateurs.
