== Description du pôle CRCI

=== Sommaire

Equipe? Travail?

Mouvance devops et lien étroit avec pôle Expertise

Experts: Supports technique transverse, formations, garant de la qualité technique des projets, mise en place de bonne pratique en s'assurant de leur exécution, responsable de la mise en place et de la maintenance des outils de production (PIC).

* Le lien entre les équipes de production et le pôle CRCI dans le calcul quantitatif des VM utiles au bon déroulement des projets et le calcul qualitatif des environnements de développement pour chaque développeur.

Infrastructure Actuelle => Infrastructure Future?

Problèmatique?

* Automatiser les déploiements

* Reporting de l'Infrastructure à tout instant (Ressources Utilisées, Problème sur les environnements)

=== Vrai

Le Pôle du CRCI -Centre de Ressources et de Compétences Informatiques- est responsable de l'infrastructure système et réseaux, de la gestion du parc et des solutions et fourni une assistance sur certains points spécifiques. Son existence et son bon fonctionnement sont primordiaux dans l'entreprise. Trois collaborateurs constituent cette équipe, *Arnaud Roudsovsky*, responsable du pôle, *Frédéric Garcia* et *Romain Ballan*.

Depuis 2015, l'entreprise a décidé de faire évoluer son infrastructure et ses méthodes de travail en s'appuyant sur le mouvement *DevOps*. Comme le présente le livre de Len Bass, Ingo Weber et Liming Zhu, DevOps est un ensemble de pratiques cherchant à réduire le temps entre la demande et la concréatisation d'une modification d'un système en production tout en assurant son bon fonctionnement [1]. Ce mouvement repose sur cinq piliers essentiels [2]:

* Culture : changer l'organisation en silos par une organisation plate et collaborative
* Automation -automatisation- : rendre autonome le déploiement les environnements de travail
* Lean : fluidifier et optimiser l'organisation et les modes d'intéractions
* Measurement -mesure- : mettre en place des indicateurs de performance adéquats et partagés par tous les métiers.
* Sharing -solidarité- : pousser à la communication et la collaboration entre les métiers

Ce nom est la contraction de _Development_ (référence au métier de développeur) et _Operation_ (référence aux différentes discpline du métier d'infogérant). Il symbolise le thème émergeant de cette culture, à savoir l'étroite collaboration de ces métiers dans la réalisation des projets.

Au sein d'ISC France, cette stratégie opérationnelle est poussé par le pôle CRCI et le pôle Expertise. Ce dernier est le garant de la qualité technique des projets de part un support technique, la dispense de formations et la mise en place de bonne pratique à exécuter par les développeurs. Dans la culture DevOps, les experts sont, notamment, responsables de la mise en place et de la maintenance des outils de production tel que la Plateforme d'Intégration Continue. Le _Continuous Delivery_ est une approche de développement en lien avec la mouvance DevOps. Il a pour but de développer, de tester et de sortir des versions de façon rapide et répeter jusqu'à avoir un logiciel de haute qualité [3]. En plus d'insuffler aux développeurs la culture DevOps, le pôle expertise est le lien entre les équipes de production et le pôle CRCI dans le calcul quantitatif des ressources utiles au bon déroulement des projets et la qualité des environnements de développement fournis à chaque développeur.

Ce souhait de changer la stratégie d'ISC France a conduit la direction, sous les conseils des pôles CRCI et expertises, à investir dans un ensemble de nouveaux matériels tels que des serveurs, des commutateurs et des baies de stockage. Depuis, l'infrastructure est hétérogène puisqu'elle regroupe quatre différentes plateformes de virtualisation. La virtualisation est un thème de plus en plus visible dans tous types d'entreprises puisque son objectif consiste à faire fonctionner plusieurs système d'exploitation sur un ou plusieurs serveurs [4]. _VMWare ESXi_ est la solution la plus ancienne de l'entreprise. Cette plateforme propriétaire est un hyperviseur de type I signifiant qu'il est installé en lieu et place d'un système d'exploitation, il permet une gestion plus efficace des environnements virtualisés tel que la migration dynamique des machines virtuels [5]. _OpenStack_ est la seconde plateforme de virtualisation utilisée par ISC France. Cette solution possède l'avantage d'être stable, déjà utilisée par des grandes entreprises aux architectures massives et complexes, et d'être _open source_, la rendant flexible à chaque utilisation [6]. Le deux dernières solutions sont basées sur l'isolation des processus dans le noyau _Linux_. Le système d'exploitation invité, appelé _container_, est contenu dans un processus isolé des autres à l'aide de deux fonctionnalités du noyau, _Cgroups_ et _Namespaces_ [7]. Le premier est _OpenVZ_, un noyau modifié Linux[8]. Le second est _Docker_ [9]