=== Pôle CRCI

Le Pôle du CRCI -Centre de Ressources et de Compétences Informatiques- est responsable de l'infrastructure système et réseaux, de la gestion du parc et des solutions logicielles et fourni une assistance sur certains points spécifiques. Trois collaborateurs constituent l'équipe du pôle de Bordeaux, *Arnaud Roudsovsky*, responsable du pôle, *Frédéric Gracia* et *Romain Ballan*. Son existence et son bon fonctionnement sont primordiaux pour l'entité.

centre de service donc infra ++


Depuis 2015, l'entreprise a décidé de faire évoluer son infrastructure et ses méthodes de travail en s'appuyant sur le mouvement _DevOps_. Comme le présente le livre de Len Bass, Ingo Weber et Liming Zhu, DevOps est un ensemble de pratiques cherchant à réduire le temps entre la demande et la concréatisation d'une modification d'un système en production tout en assurant son bon fonctionnement [1]. Ce mouvement repose sur cinq piliers essentiels comme l'énonce Joonas Hamunen dans son document [2]:

* _Culture_ : changer l'organisation en silos par une organisation plate et collaborative.
* _Automation_ -automatisation- : rendre autonome le déploiement des environnements de travail et de production.
* _Lean_ : fluidifier et optimiser l'organisation et les modes d'intéractions entre les différents acteurs.
* _Measurement_ -mesure- : mettre en place des indicateurs de performance adéquats et partagés par tous les métiers.
* _Sharing_ -solidarité- : accroitre la communication et la collaboration entre les métiers.

Ce nom est la contraction de _Development_ (référence au métier de développeur) et _Operation_ (référence aux différentes discpline du métier d'infogérant).
Il symbolise le thème émergeant de cette culture, à savoir l'étroite collaboration de ces métiers dans la réalisation des projets.

Au sein d'ISC France, cette culture est poussée par le pôle CRCI et le pôle Expertise.
Ce dernier est le garant de la qualité technique des projets de part un support technique, la dispense de formations et la mise en place de bonne pratique à exécuter par les développeurs.
Dans la culture DevOps, les experts sont, notamment, responsables de la mise en place et de la maintenance des outils de production tel que la Plateforme d'Intégration Continue.
Le _Continuous Delivery_ est une approche de développement en lien avec la mouvance DevOps.
Il a pour but de développer, de tester et de sortir des versions de façon rapide et répeter jusqu'à avoir un logiciel de haute qualité [3].
En plus d'insuffler aux développeurs la culture DevOps, le pôle expertise est le lien entre les équipes de production et le pôle CRCI dans le calcul quantitatif des ressources utiles au bon déroulement des projets et la qualité des environnements de développement fournis à chaque développeur.
