*Evolution de la plateforme de supervision et optimisation du réseau*

= Contexte Industriel

== Courte description de SQLi Groupe

== Courte description de ISC France

== Description du pôle CRCI

Equipe? Travail?

Mouvance devops et lien étroit avec pôle Expertise

Infrastructure Actuelle => Infrastructure Future?

Problèmatique?

- Automatiser les déploiements

- Reporting de l'Infrastructure à tout instant (Ressources Utilisées, Problème sur les environnements)

= Travail Principal => Upgrade Zabbix

Objectif du CRCI:

Etape 1: phase de recherche

* Recherche du logiciel adapté à nos besoin (docker, scénario web, besoin de SLAs, alerte)
* Recherche de la version : L'entreprise a pour objectif d'être à jour dans les versions de ces outils internes

Etape 2 : phase de test et mise en production

* (Server & Agent) Compréhension de l'outil (fonctionnement et utilisation globale) par la création d'une plateforme de test :
* (Server & Agent) une configuration (fichier et trigger) plus adaptée à ces besoins actuels et futurs.
* Evoqué le cas de Docker
* Remplacement du serveur
* (Agent) Avoir des versions le plus à jours possible (si possible) et une installion homogène et envoie de nouvelle conf

Conclusion sur le sujet

= Activitité Annexe

== Scripting installation + configuration Agent + Utilisation Ansible

- Besoin de déployer rapidement et efficacement l'Agent (Automatisation)

- Script batch pour windows

- Script python pour linux (Nova_Hostname)

- En l'état les VM ont une version possiblement pas à jour et une mauvaise configuration

- L'outil permet de pousser et d'exécuter des Script à un nombre de VM de masse

- Expliquer utilisation Windows et Linux.

== Scripting nombre de VM

- Infrastructure actuelle hétérogène (VMWare + Openstack)

- Besoin de connaitre l'étendue des VM et leur

- Création de 3 scripts Python (ESXi 5.0, 5.5, Openstack)
