*Evolution de la plateforme de supervision et optimisation du réseau*

= Contexte Industriel

== Courte description de SQLi Groupe

== Courte description de ISC France

== Description du pôle CRCI

Equipe? Travail?

Mouvance devops et lien étroit avec pôle Expertise

== Description de l'infrastructure

Infrastructure Actuelle => Infrastructure Future?

Problèmatique?

- Automatiser les déploiements

- Reporting de l'Infrastructure à tout instant (Ressources Utilisées, Problème sur les environnements)

= Travail Principal => Upgrade Zabbix

Objectif du CRCI:

Etape 1: phase de recherche

* Recherche du logiciel adapté à nos besoin (docker, scénario web, besoin de SLAs, alerte)
* Recherche de la version : L'entreprise a pour objectif d'être à jour dans les versions de ces outils internes

Etape 2 : phase de test et mise en production

* (Server & Agent) Compréhension de l'outil (fonctionnement et utilisation globale) par la création d'une plateforme de test :
* (Server & Agent) une configuration (fichier et trigger) plus adaptée à ces besoins actuels et futurs.
* Evoqué le cas de Docker
* Remplacement du serveur
* (Agent) Avoir des versions le plus à jours possible (si possible) et une installion homogène et envoie de nouvelle conf

Conclusion sur le sujet

= Ansible

Recherche de la solution

Mise en place:
* installation et utilisation en test
* Création scripts

Conclusion du sujet

= Annexes

* Virtualisation
* Containerisation
* Openstack
* Zabbix
* Ansible
