=== Initiation du changement

Depuis le second trimestre 2014, le pôle CRCI s'est doté d'un serveur _Zabbix_, un logiciel open source mesurant et surveillant l'infrastructure.
Cependant, l'expansion de l'activité, l'évolution de l'infrastructure et la mise en place de nouvelles pratiques issues de DevOps ont réduit le temps de l'équipe. N'étant plus maintenu, l'outil était devenu une tare de part ses alertes nombreuses, fréquentes et non importantes.
 +
A partir de ces reproches, nous avons remis en cause le logiciel utilisé en menant des recherches sur des solutions concurrentes. Ensuite, un environnement de test a été créé avant le déploiement de l'outil. Le but de cette phase était de configurer l'outil avant son utilisation sur l'infrastructure. A la fin de la mise en production de la solution, nous avons tiré un premier bilan de son utilisation.

=== Remise en cause de la solution actuelle

Pour débuter, notre première action a été de lister les objectifs actuels et futurs auxquels l'outil devra répondre.
L'infrastructure d'ISC France héberge des applications web internes. Certaines sont primordiales pour la gestion quotidienne du travail des collaborateurs, d'autres facilitent la vie de l'entreprise. Le pôle CRCI doit pouvoir recevoir une alerte quasi instantanée lorsqu'une application n'est plus accessible. La solution à envisager doit, donc, pouvoir simuler un scénario web comme un simple accès sur une page web ou une tentative de connexion.
 +
Le pôle CRCI rend un rapport chaque semaine concernant la disponibilité de l'infrastructure. Comme l'évoque le papier scientifique de Pankesh Patel, Ajith H. Ranabahu et Amit P. Sheth [10], dans une infrastructure cloud computing, il est important de posséder un accord concernant la disponibilité de la plateforme entre les consommateurs et un prestataire. Dans le cas d'ISC France, les consommateurs sont le directeur et les managers ; le prestataire est le pôle CRCI. Un _SLA_ -Service Level Agreement- doit être négocié entre les deux parties pour définir précisemment un accord sur les mesures à prendre en compte.

<<<

La mise en place de la culture DevOps a emmené l'utilisation de l'outil Docker combiné au système d'exploitation _CoreOS_, système d'exploitation léger et adapté pour l'utilisation de cet outil comme l'indique Mathijs Jeroen Scheepers [11]. La solution à choisir doit pouvoir surveiller ce genre d'environnement virtuel en minimisant les composants à installer sur le système d'exploitation de l'hôte.
 +
Enfin, cette mouvance doit pousser les équipes de développement à quantifier les ressources matérielles utilisées par les outils qu'ils développent. L'outil doit donc pouvoir fournir des graphes et des valeurs lisibles et compréhensibles à des non-initiés.

A partir de cette liste, nous avons pu nous mettre à la recherche d'un logiciel remplissant ces conditions. Il existe de nombreuses offres sur le marché. Néanmoins, très peu d'entre elles répondent entièrement à nos attentes. Notre choix s'est donc porté sur la solution déjà en place, Zabbix, pour plusieurs raisons.
 +
Ce logiciel détient les éléments de base de nos exigences, à savoir l'envoie d'alerte en cas d'indisponibilité sur une application we que nous hébergeons et le calcul de SLAs calculant la disponibilité de l'infrastructure.
De plus, l'offre est open source et possède une large communauté active offrant des fonctionnalités supplémentaires utiles à nos exigences, comme la surveillance et la mesure des ressources des environnements virtuels sous Docker.
Ensuite, la nouvelle version de ce logiciel offre une interface plus ergonomique. Cette nouveauté rendra l'utilisation des données et des graphes plus lisibles aux équipes de développement.
Enfin, les membres du pôle CRCI sont déjà formés sur cet outil. Cet avantage permet de gagner un temps considérable sur son approche basique. Cette conjoncture nous sera utile pour configurer plus précisemment la solution et mettre en place les fonctionnalités souhaitées.

=== Environnement de test et mise en production

Après le choix du logiciel, nous avons dû le déployer. Notre contrainte a été de configurer la future solution tout en gardant actif l'outil présent sur l'infrastructure. Pour cela, nous avons recréé un environnement de tests comportant le minimum d'environnement nécessaire à une configuration optimale.

<<<

Zabbix est une offre de surveillance et de mesure de l'activité infrastructurale d'une entreprise. Il est basé sur le système de client-serveur signifiant que les agents envoient au serveur les données qu'il souhaite récupérer. La solution possède trois logiciels.

** Le _Serveur_ est le centre du service. Il est composé de deux logiciels, _server_ et _frontend_. Ces outils doivent être combiné à une base de données servant à stocker les données récupérées et à un serveur web. Il héberge l'interface web permettant d'ochestrer les mesures à récupérer et de rendre leurs lectures plus simples. Le serveur Zabbix récupère les données à l'aide de requêtes réseaux utilisant le protocole _HTTP_ (combiné au format _JSON_) ou le protocole _SNMP_.
** Les _Agents_ sont les noeuds du système. Ils sont installés sur chaque environnement à monitorer. Chaque agent récupère les mesures et les envoie au serveur. Dans une infrastructure, un agent doit obligatoirement être lié à un serveur.
** Les _Proxys_ font office d'intermédiaire entre un agent et un serveur. Son but est de récolter les informations d'un groupe d'agents et de les envoyer au serveur principal. Ce logiciel peut ne pas être utilisé.

A partir de notre plateforme de tests, nous avons pu configurer notre serveur et nos agents à notre convenance. Dans un premier temps, nous avons décidé de nous passer de la fonctionnalité proxy de la solution. Il y a eu deux phases dans la configuration.
La première concernait les fichiers de configuration des agents et du serveur. Il faut que l'agent connaisse le nom de la machine sur lequel il est installé et l'adresse IP du serveur. Pour ce dernier, nous avons dû le configurer pour qu'il puisse se connecter à la base de données et rendre accessible l'interface web. De plus, nous avons dû le configurer pour qu'il démarre un nombre important de processus système afin de traiter toutes les données qui lui sont destinées.
 +
La seconde étape de configuration a été de définir ce que nous souhaitions mesurer sur chaque environnement. Cette phase se fait par l'intermédiaire de l'interface web du serveur Zabbix. On choisit des _items_ qui représentent les données à récupérer sur les agents, comme par exemple l'utilisation de la RAM. Ensuite, ces items sont utilisés pour déclencher ou non des _triggers_. Ce sont un ensemble de conditions qui provoquent une _alerte_, l'envoi d'un courriel par exemple, si elles sont vérifiées. Par exemple, si l'utilisation de la RAM dépasse les 90% du total de la machine alors une alerte est déclenchée. Enfin c'est avec ces données que les SLAs sont calculés.

<<<

Dans la configuration de la solution qui était en place, les environnements à monitorer ainsi que leurs mesures étaient enregistrés par l'équipe du pôle CRCI grâce à l'application web. Zabbix permet de rendre ces actions dynamiques. Il suffit de renseigner dans le fichier de configuration de chaque agent une liste de _métadata_. Lors du démarrage de cet outil, un échange de requêtes a lieu avec le serveur. Celui-ci enregistre la machine dans la base de données avec son nom et son adresse IP. Puis il analyse les métadas et affecte à l'agent les items. Ce gain de temps entre dans l'esprit DevOps.
 +
Comme expliqué, l'entité utilise de plus en plus le logiciel Docker. Nous possédons plusieurs environnements "Dockerisés" qui n'étaient pas surveillés par l'ancien serveur Zabbix. Nous souhaitions un système qui mesure l'activité de chaque envrionnement tout en évitant d'installer un agent dans le système d'exploitation CoreOS. Grâce à la large communauté de Zabbix, une extension a été développée. Néanmoins, celle-ci ne nous satisfaisait pas entièrement, nous avons donc décidé d'implémenter notre propre outil. Il se traduit par un container Docker dans lequel un agent et l'extension ont été compilés. Cet agent récupère les données de tous les containers s'exécutant sur la machine. Cette action est effectuée par l'intermédiaire du _socket_ du logiciel Docker. Ensuite, l'agent envoie les mesures au serveur.

A la fin de la phase de test, nous avons décidé de remplacer le serveur existant par le nouveau. La migration s'est faite en deux parties. Pour commencer, nous avons installé les logiciels serveurs sur le nouvel environnement en migrant le fichier de configuration et en important la définition des items et des trigger. Dans un second temps, il a fallu modifier la configuration de chaque agent pour qu'ils aient leurs nouvelles informations. Pour cette phase, un outil d'automatisation a été utilisé.

=== Apports et limites de cette nouvelle configuration

Après la mise en production du nouveau serveur de surveillance et le changement de configuration de tous les agents vers ce dernier. Les mesures récupérées ont été instantanées. A partir de ce moment, nous avons pu ajuster certaines mesures et alertes jugées trop sensibles et en ajouter des nouvelles.

<<<

Les apports de cette nouvelle configuration sont importants et primordiaux pour le pôle CRCI. Pour commencer, les alertes reçues, en cas de dysfonctionnement, sont précises ce qui nous permet d'intervenir rapidement et efficacement.
Ensuite, les mesures effectuées sur l'infrastructure nous donnent la capacité de suivre la consommation de chaque machine efficacement. Cette avantage nous permet d'envisager certaines optimisations. Enfin, pouvoir monitorer les environnements virtuels sous Docker est un plus pour l'évolution et la popularité de ce système dans notre infrastructure.

Malgré tout, le logiciel Zabbix n'est pas un outil parfait. Sa principale limite est le temps à consacrer dans la configuration des mesures, des alertes et des hôtes. Effectivement, un environnement virtualisé détruit de l'infrastructure n'est pas automatiquement supprimé du serveur Zabbix.
Les limites de Zabbix ainsi que l'évolution de notre infrastructure nous obligeront à garder du temps pour effectuer une veille technologique autour de cet outil et de ses composants annexes. Garder notre serveur de supervision en adéquation avec notre système est essentiel pour la bonne santé de celui-ci.

Actuellement nous utilisons une base de donnée _MySQL InnoDB_ sans réplication. Pour notre infrastructure mesurant plus de deux cent hôtes, cette configuration est suffisante. Néanmoins, elle peut s'avérer être une limite en cas d'accroissement massif du nombre d'environnement à superviser. En effet, selon les documents officiels de Zabbix, notre configuration sera optimale jusqu'à cinq cent hôtes. Notre marge de manoeurvre est encore importante. La mise en place de sauvegarde de la base de donnée serait une bonne pratique à mettre en place, dans un avenir proche. L'utilisation d'un standard _RAID_ pourrait rendre cette pratique automatique.
