=== Initiation du changement

Depuis le second trimestre 2014, le pôle CRCI s'est doté d'un serveur _Zabbix_, un logiciel open source mesurant et surveillant l'infrastructure.
Cependant, l'expansion de l'activité, l'évolution de l'infrastructure et la mise en place de bonne pratique en lien avec la culture DevOps ont réduit le temps des ingénieurs du pôle pour s'occuper du logiciel. Il était devenu une tare de part ses alertes nombreuses, fréquentes et non importantes.
 +
A partir de ces reproches, nous avons décidé de repartir du commencement et un processus de mise en production s'est déroulé en deux étapes. Pour commencer, nous avons remis en cause le logiciel par la recherche de nouvelles solutions. Ensuite, un environnement de test a été créé avant de déployer l'outil et la configuration adéquat vers l'infrastructure. Enfin un bilan sera tiré de cette nouvelle configuration pour le pôle CRCI.

=== Remise en cause de la solution actuelle

Pour débuter, notre première action a été de lister les objectifs actuels et futurs auxquels l'outil devra répondre.
L'infrastructure d'ISC France héberge des applications web internes. Certaines sont primordiales pour la gestion quotidienne du travail des collaborateurs, d'autres facilitent la vie de l'entreprise. Le pôle CRCI doit pouvoir recevoir une alerte rapide lorsque l'application n'est pas accessible. La solution à envisager doit pouvoir simuler un scénario web comme un simple accès sur une page web ou une tentative de connexion.
 +
Le pôle CRCI rend un rapport chaque semaine concernant la disponibilité de l'infrastructure. Comme l'évoque le papier scientifique de Pankesh Patel, Ajith H. Ranabahu et Amit P. Sheth [10], dans une infrastructure dite cloud computing, il est important de signer un accord de disponibilité de la plateforme entre les consommateurs et un prestataire. Dans le cas d'ISC France, les consommateurs sont le directeur, les managers et les directeurs de projet et les prestataires sont le pôle CRCI. Un _SLA_ -Service Level Agreement- doit être négocié entre les deux parties pour définir précisemment un accord sur les mesures à prendre en compte.

<<<

La mise en place de la culture DevOps a emmené l'utilisation, au sein de l'infrastructure, de l'outil Docker combiné au système d'exploitation _CoreOS_, système d'exploitation léger et adapté pour l'utilisation de cet outil comme l'indique Mathijs Jeroen Scheepers [11]. La solution à choisir doit pouvoir surveiller ce genre d'environnement virtuel sans devoir installer de composant sur le système d'exploitation.
Cette mouvance qui est en train de s'installer dans l'entreprise doit pousser les équipes de développement à quantifier les ressources matérielles utilisées par leurs programmes. L'outil doit donc pouvoir fournir des graphes et des valeurs lisibles et compréhensibles à des non-initiés à l'infogérance.

A partir de cette liste, nous avons pu nous mettre à la recherche d'un logiciel remplissant ces conditions. Il existe de nombreuses offres sur le marché. Néanmoins, très peu d'entre elles répondent entièrement à nos attentes. Notre choix s'est donc porté sur la solution que nous utilisons, Zabbix, pour plusieurs raisons.
Ce logiciel détient les éléments de base de nos exigences, à savoir l'envoie d'alerte en cas d'indisponibilité sur une application we que nous hébergeons et le calcul de SLAs calculant la disponibilité de l'infrastructure.
 +
De plus, l'offre est open source et possède une large communauté active offrant des fonctionnalités supplémentaires utiles à nos exigences, comme par exemple la surveillance et la mesure des ressources utilisées par les environnements virtuels sous Docker.
Ensuite, la nouvelle version de ce logiciel offre une interface plus ergonomique. Cette nouveauté rendra l'utilisation des données et des graphes plus lisibles aux équipes de développement.
Enfin, les membres du pôle CRCI sont déjà formés sur cet outil. Cet avantage permet de gagner un temps considérable sur son approche basique. Cette conjoncture nous sera utile pour configurer plus précisemment la solution et mettre en place les fonctionnalités souhaitées.

=== Environnement de test et mise en production

Après le choix du logiciel, nous avons dû le déployer. Notre but a été de configurer la future solution d'une manière optimale tout en gardant en fonctionnement la solution présente sur l'infrastructure. Pour cela, on a recréé un environnement de tests comportant le minimum d'environnement nécessaire à une configuration adéquate.
 +
Zabbix est une offre de surveillance et de mesure de l'activité infrastructurale d'une entreprise. Il est basé sur le système de client-serveur signifiant que l'agent, dans le cas de cette solution, envoie au serveur les données que celui-ci souhaite recevoir. La solution possède trois logiciels.

** _Serveur_ qui est le centre du service. Il est composé de deux logiciels, _server_ et _frontend_. Ces outils doivent être combiné à une base de données servant à stocker les données récupérées et à un serveur web qui permet de déployer une interface web permettant de configurer les mesures que l'on souhaite récupérer et aidant la lecture de celle-ci. Le serveur récupère les données envoyées par les protocoles _HTTP_ (en utilisant le format _JSON_) et _SNMP_.
** _Agents_ qui sont les noeuds du système. Ils sont installés sur chaque environnement à surveiller. Chaque agent récupère et envoie les mesures que lui demande le serveur. Dans une infrastructure, un agent doit obligatoirement avoir un serveur à qui il peut communiquer.
** _Proxys_ qui font office d'intermédiaire entre un agent et un serveur. Son but est de récolter les informations d'un groupe d'agents et de les envoyer au serveur principal. Ce logiciel peut ne pas être utilisé.

A partir de notre plateforme de tests, on a pu configurer notre serveur et nos agents à notre convenance. Dans un premier temps, nous avons décidé de nous passer de la fonctionnalité proxy de la solution. Il y a eu deux phases dans la configuration.
La première concerne les fichiers de configuration des agents et du serveur. Il faut que l'agent connaisse le nom de la machine sur lequel il est installé et l'adresse IP du serveur. Pour ce dernier, nous avons dû le configurer pour qu'il puisse se connecter à la base de données et que l'interface web soit accessible. De plus, nous avons dû le configurer pour qu'il démarre assez de processus système afin de traiter toutes les données qui lui sont destinées.
 +
La seconde étape de configuration a été de définir ce que l'on souhaitait mesurer sur chaque environnement. Cette phase se fait par l'intermédiaire de l'interface web du serveur Zabbix. On choisit des _items_ qui représentent une donnée à récupérer sur les agents, comme par exemple l'utilisation de la RAM. Ensuite, ces items sont utilisés pour déclencher ou non des _triggers_. Ce sont un ensemble de conditions qui provoquent une _alerte_, courriel par exemple,  si elles sont vérifiées. Par exemple, si l'utilisation de la RAM dépasse les 90% du total alors une alerte est déclenchée. Enfin c'est avec ces données que les SLAs demandés sont calculés.

<<<

Dans la configuration de la solution qui était en place sur l'infrastructure, les environnements à monitorer ainsi que leurs mesures étaient enregistrés par l'équipe du pôle CRCI grâce à l'application web du serveur. Zabbix permet de rendre ces actions dynamiques. Il suffit de renseigner dans le fichier de configuration de chaque agent une liste de _métadata_. Lors du lancement du service sur l'agent, un échange de requêtes a lieu avec le serveur. Celui-ci enregistre la machine dans la base de données avec son nom et son adresse IP. Puis il analyse les métadas et affecte à l'agent les items souhaités. Ce gain de temps entre dans l'esprit DevOps.
 +
Comme expliqué, l'entité utilise de plus en plus le logiciel Docker. Nous possédons plusieurs environnements "Dockerisés" qui n'étaient pas surveillés par l'ancien serveur Zabbix. Nous souhaitions un système qui mesure l'activité de chaque envrionnement tout en évitant d'installer un agent dans le système d'exploitation CoreOS. Grâce à la communauté active, nous avons trouvé une fonctionnalité qui a pu contenter nos attentes. Grâce à la large communauté de Zabbix, une solution a été développée. Néanmoins, celle-ci ne nous satisfaisait pas entièrement, nous avons donc décidé d'implémenter notre propre outil. Il se traduit par un container Docker dans lequel un agent et le composant ont été compilés. Cet agent récupère les données de tous les containers s'exécutant sur la machine. Cette action est effectuée par l'intermédiaire du _socket_ du logiciel Docker. Ensuite, il envoie les mesures au serveur.

A la fin de la phase de test, nous avons décidé de remplacer le serveur existant par le nouveau. La migration s'est faite en deux parties. Pour commencer, nous avons installé les logiciels serveurs sur le nouvel environnement. Puis, il a fallu migrer le fichier de configuration du serveur test. Enfin, une importation de la saisie des items et des triggers du serveur de test a dû être effectué. Dans un second temps, il a fallu modifier la configuration de chaque agent pour qu'ils aient leurs nouvelles informations. Pour cette phase, un outil d'automatisation a été utilisé.

=== Apports et limites de cette nouvelle configuration

Après la mise en production du nouveau serveur de surveillance et le changement de configuration de tous les agents vers ce dernier. Les mesures récupérées ont été instantanées. A partir de ce moment, on a pu ajuster certaines mesures et alertes jugées sans intérêts ou trop sensibles et en ajouter des nouvelles.

<<<

Les apports de cette nouvelle configuration sont importants et primordiaux pour le pôle CRCI. Pour commencer, les alertes reçues en cas de problème sur les environnements surveillés sont précises ce qui nous permet d'intervenir rapidement et efficacement.
Ensuite, les mesures effectuées sur l'infrastructure nous donnent la capacité de suivre la consommation de chaque machine efficacement. Cette avantage nous offre la possibilité de l'optimiser.

Enfin, pouvoir monitorer les environnements virtuels sous Docker est un plus pour l'évolution et la popularité de ce système dans notre infrastructure.
Malgré tout, le logiciel Zabbix n'est pas un outil parfait. Sa principale limite est le temps à consacrer dans la configuration des mesures, des alertes et des hôtes. Effectivement, une machine qui a été supprimée sur l'infrastructure ne l'est pas sur le serveur.
Les limites de Zabbix ainsi que l'évolution de notre infrastructure nous obligeront à garder du temps pour effectuer une veille technologique autour de cet outil et de ses composants annexes. Garder notre serveur de supervision en adéquation avec notre système est essentiel pour la bonne santé de celui-ci.

Actuellement nous utilisons une base de donnée _MySQL InnoDB_ sans réplication. Pour notre infrastructure mesurant plus de deux cent hôtes, cette configuration est suffisante. Cependant, elle peut s'avérer être une limite en cas d'accroissement massif de l'infrastructure à superviser. En effet, selon les documents officiels de Zabbix, notre configuration sera optimale jusqu'à cinq cent hôtes. Notre marge de manoeurvre est encore importante. Néanmoins, la mise en place de sauvegarde de la base de donnée serait une bonne pratique à mettre en place. L'utilisation d'un standard _RAID_ pourrait rendre cette pratique automatique.
